# Neural Networks with Keras

In [1]:
import pandas as pd
from pandas import read_csv
import numpy as np
import datetime as dt
from datetime import datetime
pd.set_option("display.max_columns", 500)
import time
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sqlalchemy import create_engine
import psycopg2
import json
from postgreSQLpassword import passW

/Users/luisfdosanchez/anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/luisfdosanchez/anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/luisfdosanchez/anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/

In [2]:
# Set the seed value for the notebook so the results are reproducible
from numpy.random import seed
seed(42)

In [3]:
connection_string = "postgresql://postgres:"+passW+"@localhost:5432/newecobici"
engine = create_engine(connection_string)

In [4]:
conn = psycopg2.connect(database="newecobici",user="postgres", password=passW, host ="localhost",port="5432")
print("Database Connected...")

Database Connected...


In [5]:
cursor=conn.cursor()

In [6]:
data=pd.read_sql_query("Select id, genero_usuario, edad_usuario, bici, ciclo_estacion_retiro, cast(fecha_retiro as VARCHAR), mes_retiro, anio_retiro, cast(hora_retiro as VARCHAR), ciclo_estacion_arribo, cast(fecha_arribo as VARCHAR), cast(hora_arribo as VARCHAR) from ecobicidf where anio_retiro in ('2017', '2018', '2019')",conn)
data=data.sample(replace=False,frac=0.08)

In [7]:
conn.close()

In [8]:
base1=data

In [9]:
data['anio_retiro'].unique()

data.head()

id genero_usuario  edad_usuario   bici  ciclo_estacion_retiro  \
3566392   41919190              M            25   7230                    199   
4922715   43278918              M            35   3865                     16   
10045228  48421523              M            33  10455                     68   
4221180   42575423              M            30   8732                    195   
24353507  64858409              F            26  11063                    153   

         fecha_retiro  mes_retiro  anio_retiro hora_retiro  \
3566392    2017-05-15           5         2017    18:10:52   
4922715    2017-07-02           7         2017    13:51:55   
10045228   2018-01-26           1         2018    17:50:22   
4221180    2017-06-07           6         2017    07:39:28   
24353507   2019-03-01           3         2019    09:33:14   

          ciclo_estacion_arribo fecha_arribo hora_arribo  
3566392                     322   2017-05-15    18:44:01  
4922715                      15   2017-07-02    14:16:30  
10045228                     84   2018-01-26    17:56:41  
4221180                     174   2017-06-07    07:59:00  
24353507                     30   2019-03-01    09:46:16

In [10]:
data['fecha_arribo2']=data['fecha_arribo']+" "+data['hora_arribo']
data['fecha_retiro2']=data['fecha_retiro']+" "+data['hora_retiro']

data['fecha_retiro']=pd.to_datetime(data['fecha_retiro'], format="%Y-%m-%d")
data['fecha_arribo']=pd.to_datetime(data['fecha_arribo'], format="%Y-%m-%d")

In [11]:
data['anio_retiro']=data.fecha_retiro.dt.year
data['mes_retiro']=data.fecha_retiro.dt.month
data['dianum_retiro']=data.fecha_retiro.dt.day
data['diasem_retiro']=data.fecha_retiro.dt.dayofweek

data['anio_arribo']=data.fecha_arribo.dt.year
data['mes_arribo']=data.fecha_arribo.dt.month
data['dianum_arribo']=data.fecha_arribo.dt.day
data['diasem_arribo']=data.fecha_arribo.dt.dayofweek

In [12]:
data['timeElapsed'] = pd.to_datetime(data['fecha_arribo2'])-pd.to_datetime(data['fecha_retiro2'])
data['timeElapsed'] = data['timeElapsed'].dt.seconds

data['fecha_arribo2']=pd.to_datetime(data['fecha_arribo2'])
data['fecha_retiro2']=pd.to_datetime(data['fecha_retiro2'])

data['hora_retiro2']=data['fecha_retiro2']-data['fecha_retiro']
data['hora_retiro2']=data['hora_retiro2'].dt.seconds

In [13]:
data['ciclo_estacion_arribo']=pd.to_numeric(data['ciclo_estacion_arribo'])

In [14]:
data.dtypes

id                                int64
genero_usuario                   object
edad_usuario                      int64
bici                             object
ciclo_estacion_retiro             int64
fecha_retiro             datetime64[ns]
mes_retiro                        int64
anio_retiro                       int64
hora_retiro                      object
ciclo_estacion_arribo             int64
fecha_arribo             datetime64[ns]
hora_arribo                      object
fecha_arribo2            datetime64[ns]
fecha_retiro2            datetime64[ns]
dianum_retiro                     int64
diasem_retiro                     int64
anio_arribo                       int64
mes_arribo                        int64
dianum_arribo                     int64
diasem_arribo                     int64
timeElapsed                       int64
hora_retiro2                      int64
dtype: object

In [15]:
data.head()

id genero_usuario  edad_usuario   bici  ciclo_estacion_retiro  \
3566392   41919190              M            25   7230                    199   
4922715   43278918              M            35   3865                     16   
10045228  48421523              M            33  10455                     68   
4221180   42575423              M            30   8732                    195   
24353507  64858409              F            26  11063                    153   

         fecha_retiro  mes_retiro  anio_retiro hora_retiro  \
3566392    2017-05-15           5         2017    18:10:52   
4922715    2017-07-02           7         2017    13:51:55   
10045228   2018-01-26           1         2018    17:50:22   
4221180    2017-06-07           6         2017    07:39:28   
24353507   2019-03-01           3         2019    09:33:14   

          ciclo_estacion_arribo fecha_arribo hora_arribo       fecha_arribo2  \
3566392                     322   2017-05-15    18:44:01 2017-05-15 18:44:01   
4922715                      15   2017-07-02    14:16:30 2017-07-02 14:16:30   
10045228                     84   2018-01-26    17:56:41 2018-01-26 17:56:41   
4221180                     174   2017-06-07    07:59:00 2017-06-07 07:59:00   
24353507                     30   2019-03-01    09:46:16 2019-03-01 09:46:16   

               fecha_retiro2  dianum_retiro  diasem_retiro  anio_arribo  \
3566392  2017-05-15 18:10:52             15              0         2017   
4922715  2017-07-02 13:51:55              2              6         2017   
10045228 2018-01-26 17:50:22             26              4         2018   
4221180  2017-06-07 07:39:28              7              2         2017   
24353507 2019-03-01 09:33:14              1              4         2019   

          mes_arribo  dianum_arribo  diasem_arribo  timeElapsed  hora_retiro2  
3566392            5             15              0         1989         65452  
4922715            7              2              6         1475         49915  
10045228           1             26              4          379         64222  
4221180            6              7              2         1172         27568  
24353507           3              1              4          782         34394

In [16]:
X=data[['genero_usuario','edad_usuario','ciclo_estacion_retiro','hora_retiro2','anio_retiro','mes_retiro','dianum_retiro','diasem_retiro','timeElapsed']]
X=X.reset_index()

In [17]:
y=data['ciclo_estacion_arribo']
y

3566392     322
4922715      15
10045228     84
4221180     174
24353507     30
           ... 
1978683      42
8643372     229
8161988      66
24682377      7
7655523     266
Name: ciclo_estacion_arribo, Length: 2007714, dtype: int64

In [18]:
X.sort_index(axis=0)

index genero_usuario  edad_usuario  ciclo_estacion_retiro  \
0         3566392              M            25                    199   
1         4922715              M            35                     16   
2        10045228              M            33                     68   
3         4221180              M            30                    195   
4        24353507              F            26                    153   
...           ...            ...           ...                    ...   
2007709   1978683              M            29                     36   
2007710   8643372              M            43                    227   
2007711   8161988              M            30                    447   
2007712  24682377              M            26                     43   
2007713   7655523              F            28                     21   

         hora_retiro2  anio_retiro  mes_retiro  dianum_retiro  diasem_retiro  \
0               65452         2017           5             15              0   
1               49915         2017           7              2              6   
2               64222         2018           1             26              4   
3               27568         2017           6              7              2   
4               34394         2019           3              1              4   
...               ...          ...         ...            ...            ...   
2007709         37821         2017           3             14              1   
2007710         64401         2017          11             23              3   
2007711         33762         2017          11              6              0   
2007712         41642         2019           3             14              3   
2007713         74220         2017          10             17              1   

         timeElapsed  
0               1989  
1               1475  
2                379  
3               1172  
4                782  
...              ...  
2007709          332  
2007710          236  
2007711          317  
2007712          846  
2007713         1202  

[2007714 rows x 10 columns]

In [19]:
y

3566392     322
4922715      15
10045228     84
4221180     174
24353507     30
           ... 
1978683      42
8643372     229
8161988      66
24682377      7
7655523     266
Name: ciclo_estacion_arribo, Length: 2007714, dtype: int64

In [20]:
le = LabelEncoder()
le.fit(y)
y_enc = le.transform(y)
y_enc

array([321,  14,  83, ...,  65,   6, 265])

0      321
1       14
2       83
3      173
4       29
      ... 
480    484
481    455
482    483
483    480
484    482
Name: 0, Length: 485, dtype: int64

In [39]:
#pd.DataFrame(y.unique()).merge(pd.DataFrame(y_enc).drop_duplicates().reset_index()[0],right_index=True,left_index=True).rename(columns={'0_x':'estacionOrig','0_y':'estacionCoded'}).to_csv('yEstaciones.csv',index=False)

In [21]:
enc = OneHotEncoder(handle_unknown='ignore')
enc_df = pd.DataFrame(enc.fit_transform(X[['genero_usuario']]).toarray())
enc_df=enc_df.rename(columns={0: "Female", 1: "Male"})
bridge_df = X.merge(enc_df,right_index=True,left_index=True)
bridge_df.sort_index(axis=0)

index genero_usuario  edad_usuario  ciclo_estacion_retiro  \
0         3566392              M            25                    199   
1         4922715              M            35                     16   
2        10045228              M            33                     68   
3         4221180              M            30                    195   
4        24353507              F            26                    153   
...           ...            ...           ...                    ...   
2007709   1978683              M            29                     36   
2007710   8643372              M            43                    227   
2007711   8161988              M            30                    447   
2007712  24682377              M            26                     43   
2007713   7655523              F            28                     21   

         hora_retiro2  anio_retiro  mes_retiro  dianum_retiro  diasem_retiro  \
0               65452         2017           5             15              0   
1               49915         2017           7              2              6   
2               64222         2018           1             26              4   
3               27568         2017           6              7              2   
4               34394         2019           3              1              4   
...               ...          ...         ...            ...            ...   
2007709         37821         2017           3             14              1   
2007710         64401         2017          11             23              3   
2007711         33762         2017          11              6              0   
2007712         41642         2019           3             14              3   
2007713         74220         2017          10             17              1   

         timeElapsed  Female  Male  
0               1989     0.0   1.0  
1               1475     0.0   1.0  
2                379     0.0   1.0  
3               1172     0.0   1.0  
4                782     1.0   0.0  
...              ...     ...   ...  
2007709          332     0.0   1.0  
2007710          236     0.0   1.0  
2007711          317     0.0   1.0  
2007712          846     0.0   1.0  
2007713         1202     1.0   0.0  

[2007714 rows x 12 columns]

In [22]:
enc = OneHotEncoder(handle_unknown='ignore')
enc_df = pd.DataFrame(enc.fit_transform(X[['ciclo_estacion_retiro']]).toarray())
bridge_df = bridge_df.merge(enc_df,right_index=True,left_index=True)
bridge_df.sort_index(axis=0)

index genero_usuario  edad_usuario  ciclo_estacion_retiro  \
0         3566392              M            25                    199   
1         4922715              M            35                     16   
2        10045228              M            33                     68   
3         4221180              M            30                    195   
4        24353507              F            26                    153   
...           ...            ...           ...                    ...   
2007709   1978683              M            29                     36   
2007710   8643372              M            43                    227   
2007711   8161988              M            30                    447   
2007712  24682377              M            26                     43   
2007713   7655523              F            28                     21   

         hora_retiro2  anio_retiro  mes_retiro  dianum_retiro  diasem_retiro  \
0               65452         2017           5             15              0   
1               49915         2017           7              2              6   
2               64222         2018           1             26              4   
3               27568         2017           6              7              2   
4               34394         2019           3              1              4   
...               ...          ...         ...            ...            ...   
2007709         37821         2017           3             14              1   
2007710         64401         2017          11             23              3   
2007711         33762         2017          11              6              0   
2007712         41642         2019           3             14              3   
2007713         74220         2017          10             17              1   

         timeElapsed  Female  Male    0    1    2    3    4    5    6    7  \
0               1989     0.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1               1475     0.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2                379     0.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3               1172     0.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4                782     1.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...              ...     ...   ...  ...  ...  ...  ...  ...  ...  ...  ...   
2007709          332     0.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007710          236     0.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007711          317     0.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007712          846     0.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007713         1202     1.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

           8    9   10   11   12   13   14   15   16   17   18   19   20   21  \
0        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2007709  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007710  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007711  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007712  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007713  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

          22   23   24   25   26   27   28   29   30   31   32   33   34   35  \
0        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2        0.0  0.0  0.

In [23]:
bridge_df.shape

(2007714, 496)

In [24]:
X=bridge_df.iloc[:,2:]

In [25]:
X=X[[col for col in X.columns if col!="ciclo_estacion_retiro"]]

In [26]:
X

edad_usuario  hora_retiro2  anio_retiro  mes_retiro  dianum_retiro  \
0                  25         65452         2017           5             15   
1                  35         49915         2017           7              2   
2                  33         64222         2018           1             26   
3                  30         27568         2017           6              7   
4                  26         34394         2019           3              1   
...               ...           ...          ...         ...            ...   
2007709            29         37821         2017           3             14   
2007710            43         64401         2017          11             23   
2007711            30         33762         2017          11              6   
2007712            26         41642         2019           3             14   
2007713            28         74220         2017          10             17   

         diasem_retiro  timeElapsed  Female  Male    0    1    2    3    4  \
0                    0         1989     0.0   1.0  0.0  0.0  0.0  0.0  0.0   
1                    6         1475     0.0   1.0  0.0  0.0  0.0  0.0  0.0   
2                    4          379     0.0   1.0  0.0  0.0  0.0  0.0  0.0   
3                    2         1172     0.0   1.0  0.0  0.0  0.0  0.0  0.0   
4                    4          782     1.0   0.0  0.0  0.0  0.0  0.0  0.0   
...                ...          ...     ...   ...  ...  ...  ...  ...  ...   
2007709              1          332     0.0   1.0  0.0  0.0  0.0  0.0  0.0   
2007710              3          236     0.0   1.0  0.0  0.0  0.0  0.0  0.0   
2007711              0          317     0.0   1.0  0.0  0.0  0.0  0.0  0.0   
2007712              3          846     0.0   1.0  0.0  0.0  0.0  0.0  0.0   
2007713              1         1202     1.0   0.0  0.0  0.0  0.0  0.0  0.0   

           5    6    7    8    9   10   11   12   13   14   15   16   17   18  \
0        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2007709  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007710  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007711  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007712  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007713  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

          19   20   21   22   23   24   25   26   27   28   29   30   31   32  \
0        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2007709  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007710  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007711  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007712  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2007713  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

          33   34   35   36   37   38   39   40   41   42   43   44   45   46  \
0        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1        0.0  0

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y_enc, random_state=1)

In [28]:
X_scaler = MinMaxScaler()
X_train_scaled=X_scaler.fit_transform(X_train)
X_test_scaled=X_scaler.fit_transform(X_test)

In [32]:
X_train_scaled

array([[0.23529412, 0.36793676, 0.5       , ..., 0.        , 0.        ,
        0.        ],
       [0.14705882, 0.60745619, 0.5       , ..., 0.        , 0.        ,
        0.        ],
       [0.16176471, 0.367196  , 0.5       , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.33823529, 0.3566402 , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.41176471, 0.83335262, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.54411765, 0.33158175, 0.5       , ..., 0.        , 0.        ,
        0.        ]])

In [30]:
len(np.unique(y.tolist()))

485

In [39]:
model = Sequential()

In [38]:
X.shape[1]

493

In [40]:
number_inputs = X.shape[1]
number_hidden_nodes =100
model.add(Dense(units=number_hidden_nodes,
                activation='relu', input_dim=number_inputs))
model.add(Dense(units=800, activation='relu'))
model.add(Dense(units=600, activation='relu'))

In [41]:
number_classes = len(np.unique(y.tolist()))
model.add(Dense(units=number_classes, activation='softmax'))

In [42]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 100)               49400     
_________________________________________________________________
dense_5 (Dense)              (None, 800)               80800     
_________________________________________________________________
dense_6 (Dense)              (None, 600)               480600    
_________________________________________________________________
dense_7 (Dense)              (None, 485)               291485    
Total params: 902,285
Trainable params: 902,285
Non-trainable params: 0
_________________________________________________________________


In [43]:
# Use categorical crossentropy for categorical data and mean squared error for regression
# Hint: your output layer in this example is using software for logistic regression (categorical)
# If your output layer activation was `linear` then you may want to use `mse` for loss
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [44]:
# Fit (train) the model
history=model.fit(
    X_train_scaled,
    y_train,
    validation_data=(X_test_scaled,y_test),
    epochs=100,
    shuffle=True,
    verbose=9,
    workers=8,
    use_multiprocessing=True,
    batch_size=300
)
model.save("bikeflux_model.h5")

Train on 1505785 samples, validate on 501929 samples
Epoch 1/100
Epoch 2/100
Epoch 3/100
Epoch 4/100
Epoch 5/100
Epoch 6/100
Epoch 7/100
Epoch 8/100
Epoch 9/100
Epoch 10/100
Epoch 11/100
Epoch 12/100
Epoch 13/100
Epoch 14/100
Epoch 15/100
Epoch 16/100
Epoch 17/100
Epoch 18/100
Epoch 19/100
Epoch 20/100
Epoch 21/100
Epoch 22/100
Epoch 23/100
Epoch 24/100
Epoch 25/100
Epoch 26/100
Epoch 27/100
Epoch 28/100
Epoch 29/100
Epoch 30/100
Epoch 31/100
Epoch 32/100
Epoch 33/100
Epoch 34/100
Epoch 35/100
Epoch 36/100
Epoch 37/100
Epoch 38/100
Epoch 39/100
Epoch 40/100
Epoch 41/100
Epoch 42/100
Epoch 43/100
Epoch 44/100
Epoch 45/100
Epoch 46/100
Epoch 47/100
Epoch 48/100
Epoch 49/100
Epoch 50/100
Epoch 51/100
Epoch 52/100
Epoch 53/100
Epoch 54/100
Epoch 55/100
Epoch 56/100
Epoch 57/100
Epoch 58/100
Epoch 59/100
Epoch 60/100
Epoch 61/100
Epoch 62/100
Epoch 63/100
Epoch 64/100
Epoch 65/100
Epoch 66/100
Epoch 67/100
Epoch 68/100
Epoch 69/100
Epoch 70/100
Epoch 71/100
Epoch 72/100
Epoch 73/100
Epoch 7

In [45]:
# Evaluate the model using the testing data
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

501929/501929 - 115s - loss: 4.2713 - acc: 0.1509
Loss: 4.271278908885854, Accuracy: 0.15085002779960632


In [46]:
y_predict = model.predict_classes(X_test_scaled)

In [47]:
y_predict

array([ 95,   5, 394, ...,  46, 133,  13])

In [48]:
y_test

array([ 31,   5, 394, ..., 167,  23,  27])

In [49]:
y_proba=model.predict_proba(X_test_scaled)
y_proba

array([[4.98576323e-03, 7.30706751e-03, 7.68425316e-03, ...,
        9.76981964e-14, 8.46795304e-14, 1.00221680e-20],
       [1.88293830e-01, 2.33406908e-07, 3.77886184e-03, ...,
        1.27498582e-20, 1.34582463e-23, 0.00000000e+00],
       [4.62547660e-34, 0.00000000e+00, 0.00000000e+00, ...,
        1.04065502e-14, 9.50638523e-16, 4.95274570e-35],
       ...,
       [2.17875865e-07, 4.73627661e-05, 2.47804936e-11, ...,
        1.70386583e-17, 9.12079701e-18, 8.12450607e-24],
       [1.06034895e-04, 4.18552197e-08, 5.77935425e-04, ...,
        5.94345943e-20, 3.54453330e-22, 0.00000000e+00],
       [2.50422931e-03, 7.70682993e-04, 3.83496506e-08, ...,
        5.28551868e-19, 2.10743551e-20, 7.19701196e-37]], dtype=float32)

In [50]:
y_proba[0,:]

array([4.98576323e-03, 7.30706751e-03, 7.68425316e-03, 6.57934370e-03,
       2.77572568e-03, 1.27534603e-03, 1.44608635e-02, 3.53278965e-03,
       3.40615795e-03, 6.80694869e-03, 1.72037212e-03, 2.47988151e-03,
       6.91856258e-03, 1.79859400e-02, 1.54628083e-02, 1.04197422e-02,
       3.86210950e-03, 6.10062713e-03, 4.47055185e-03, 1.18054543e-03,
       4.02549841e-03, 7.04064127e-03, 1.50792524e-02, 1.89237781e-02,
       2.52056797e-03, 1.16455117e-02, 6.62731705e-03, 4.59943227e-02,
       1.44301420e-02, 2.17093504e-03, 2.17596767e-03, 1.03069069e-02,
       4.89208240e-12, 1.44169573e-03, 3.11088655e-03, 8.36636033e-03,
       1.49892541e-02, 8.42079241e-03, 9.42383707e-03, 1.62793032e-03,
       1.85082536e-02, 8.27627350e-03, 5.21785691e-02, 2.03635730e-03,
       9.96967684e-03, 4.78998572e-03, 1.32819610e-02, 1.36280376e-02,
       6.53889379e-04, 1.39840576e-03, 6.65898807e-03, 1.44746741e-02,
       3.66024506e-05, 3.61133576e-03, 1.18799787e-02, 4.49326541e-03,
      

In [51]:
y_probtopd=pd.DataFrame(data=y_proba[:,:])

In [52]:
y_probtopd.sum(axis = 0, skipna = True) 

0      5143.061035
1      1496.048584
2      1664.168701
3      1625.252075
4      1339.708130
          ...     
480       0.449125
481       7.913239
482       0.000613
483       3.001385
484       2.885335
Length: 485, dtype: float32

In [53]:
y_probtopd.sum(axis = 0, skipna = True).sum(axis = 0, skipna = True) 

501859.53